version: '3'

services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: FISHOLOGY
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - docker_network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - docker_network

  data_generator:
    image: python:alpine3.19
    volumes:
      - ./data_generator/:/app
      - ./utils:/app/utils
    working_dir: /app
    command: >
      sh -c "pip install -r requirements.txt && python -u main.py"
    networks:
      - docker_network
    depends_on:
      - database

  api:
    image: python:alpine3.19
    volumes:
      - ./api/:/app
      - ./utils:/app/utils
    working_dir: /app
    command: >
      sh -c "pip install -r requirements.txt && python -u main.py"
    ports:
      - "5000:5000"
    networks:
      - docker_network
    depends_on:
      - database

networks:
  docker_network:
    driver: bridge
